[package]
name = "boardgame"
version = "0.1.0"
authors = [
  "Christian Michael Paul Bankester <cbankester@immense.net>"
]

[[bin]]
name = "spinning-square"

[dependencies]
piston = "0.17.0"
piston2d-graphics = "0.13.0"
pistoncore-glutin_window = "0.20.0"
piston2d-opengl_graphics = "0.23.0"
